<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Ticketslist.aspx.cs" Inherits="UshaOnlineServiceCenter.Ticketslist" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
         <h2 class="auto-style1">
                <img alt="" class="auto-style2" src="ushal.PNG" /></h2>
        <h2>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Tickets List</h2>
        
        <div>
            <asp:GridView runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" ID="grdview" OnRowEditing="grdview_RowEditing" OnRowUpdating="grdview_RowUpdating" OnRowDeleting="grdview_RowDeleting" CellPadding="4" ForeColor="#333333" GridLines="None" DataKeyNames="Id" Height="100px">
            
                <AlternatingRowStyle BackColor="White" width="100px" />
           
               <Columns>
                   
                   <asp:TemplateField HeaderText="id" Visible="false" >
<EditItemTemplate>
<asp:Label ID="lbleditusr" runat="server" Text='<%#Eval("id") %>'/>
</EditItemTemplate>
<ItemTemplate>
<asp:Label ID="lblitemUsr" runat="server" Text='<%#Eval("id") %>'/>
</ItemTemplate>
                       </asp:TemplateField>
             
    <asp:TemplateField HeaderText="Salutation">
      <ItemTemplate>
         <asp:Label ID="lblsalutation" runat="server" Text='<%#Eval("Salutation") %>'/>
     </ItemTemplate>
     <EditItemTemplate>
         <asp:TextBox ID="txtstatution" width="70px"  runat="server" Text='<%#Eval("Salutation") %>'/>
     </EditItemTemplate>
     
 </asp:TemplateField>
 <asp:TemplateField HeaderText="Name">
      <ItemTemplate>
         <asp:Label ID="lblname" runat="server" Text='<%#Eval("Name") %>'/>
     </ItemTemplate>
     <EditItemTemplate>
         <asp:TextBox ID="txtname" width="70px"  runat="server" Text='<%#Eval("Name") %>'/>
     </EditItemTemplate>
     
 </asp:TemplateField>
 <asp:TemplateField HeaderText="Email">
     <ItemTemplate>
         <asp:Label ID="lblmail" runat="server" Text='<%#Eval("Email") %>'/>
     </ItemTemplate>
     <EditItemTemplate>
         <asp:TextBox ID="txtmail" width="70px"  runat="server" Text='<%#Eval("Email") %>'/>
     </EditItemTemplate>
    
 </asp:TemplateField>
  <asp:TemplateField HeaderText="Mobileno">
       <ItemTemplate>
         <asp:Label ID="lblmobileno" runat="server" Text='<%#Eval("Mobileno") %>'/>
     </ItemTemplate>
     <EditItemTemplate>
         <asp:TextBox ID="txtmobileno" width="50px"   runat="server" Text='<%#Eval("Mobileno") %>'/>
     </EditItemTemplate>
    
 </asp:TemplateField>
   <asp:TemplateField HeaderText="Address1">
     <ItemTemplate>
         <asp:Label ID="lbladdress1" runat="server" Text='<%#Eval("Address1") %>'/>
     </ItemTemplate>
     <EditItemTemplate>
         <asp:TextBox ID="txtaddress1" width="30px"  runat="server" Text='<%#Eval("Address1") %>'/>
     </EditItemTemplate>
   
 </asp:TemplateField>
    <asp:TemplateField HeaderText="Address2">
     <ItemTemplate>
         <asp:Label ID="lbladdress2" runat="server" Text='<%#Eval("Address2") %>'/>
     </ItemTemplate>
    <EditItemTemplate>
         <asp:TextBox ID="txtaddress2" width="30px"  runat="server" Text='<%#Eval("Address2") %>'/>
     </EditItemTemplate>
   
 </asp:TemplateField>
  
    <asp:TemplateField HeaderText="Preffered Languague">
     <ItemTemplate>
         <asp:Label ID="lblpreffered" runat="server" Text='<%#Eval("PrefferedLanguague") %>'/>
     </ItemTemplate>
    <EditItemTemplate>
         <asp:TextBox ID="txtprefferedlang" width="30px"  runat="server" Text='<%#Eval("PrefferedLanguague") %>'/>
     </EditItemTemplate>
   
 </asp:TemplateField>
    
    <asp:TemplateField HeaderText="States">
     <ItemTemplate>
         <asp:Label ID="lblstate" runat="server" Text='<%#Eval("States") %>'/>
     </ItemTemplate>
    <EditItemTemplate>
         <asp:TextBox ID="txtstate" width="30px"  runat="server" Text='<%#Eval("States") %>'/>
     </EditItemTemplate>
   
 </asp:TemplateField>
   
    <asp:TemplateField HeaderText="City">
     <ItemTemplate>
         <asp:Label ID="lblcity" runat="server" Text='<%#Eval("City") %>'/>
     </ItemTemplate>
    <EditItemTemplate>
         <asp:TextBox ID="txtcity" width="30px"  runat="server" Text='<%#Eval("City") %>'/>
     </EditItemTemplate>
   
 </asp:TemplateField>
     <asp:TemplateField HeaderText="Locality">
     <ItemTemplate>
         <asp:Label ID="lbllocality" runat="server" Text='<%#Eval("Locality") %>'/>
     </ItemTemplate>
    <EditItemTemplate>
         <asp:TextBox ID="txtlocality" width="30px"  runat="server" Text='<%#Eval("Locality") %>'/>
     </EditItemTemplate>
   
 </asp:TemplateField>
     <asp:TemplateField HeaderText="Pincode">
     <ItemTemplate>
         <asp:Label ID="lblpincode" runat="server" Text='<%#Eval("Pincode") %>'/>
     </ItemTemplate>
    <EditItemTemplate>
         <asp:TextBox ID="txtpincode" width="30px"  runat="server" Text='<%#Eval("Pincode") %>'/>
     </EditItemTemplate>
 </asp:TemplateField>
   
          <asp:TemplateField HeaderText="ProductCategory">
     <ItemTemplate>
         <asp:Label ID="lblproduct" runat="server" Text='<%#Eval("ProductCategory") %>'/>
     </ItemTemplate>
    <EditItemTemplate>
         <asp:TextBox ID="txtproductcategory" width="30px"  runat="server" Text='<%#Eval("ProductCategory") %>'/>
     </EditItemTemplate>
   
 </asp:TemplateField>

    <asp:TemplateField HeaderText="Product">
     <ItemTemplate>
         <asp:Label ID="Label1" runat="server" Text='<%#Eval("Product") %>'/>
     </ItemTemplate>
    <EditItemTemplate>
         <asp:TextBox ID="txtproduct" width="30px"  runat="server" Text='<%#Eval("Product") %>'/>
     </EditItemTemplate>
   
 </asp:TemplateField>

    <asp:TemplateField HeaderText="Model">
     <ItemTemplate>
         <asp:Label ID="lblmodel" runat="server" Text='<%#Eval("Model") %>'/>
     </ItemTemplate>
    <EditItemTemplate>
         <asp:TextBox ID="txtmodel" width="30px"  runat="server" Text='<%#Eval("Model") %>'/>
     </EditItemTemplate>
   
 </asp:TemplateField>

    <asp:TemplateField HeaderText="PurchaseSource">
     <ItemTemplate>
         <asp:Label ID="lblpurchase" runat="server" Text='<%#Eval("PurchaseSource") %>'/>
     </ItemTemplate>
    <EditItemTemplate>
         <asp:TextBox ID="txtpurchasesource" width="30px"  runat="server" Text='<%#Eval("PurchaseSource") %>'/>
     </EditItemTemplate>
   
 </asp:TemplateField>
 
    <asp:TemplateField HeaderText="YourSupportRequest">
     <ItemTemplate>
         <asp:Label ID="lblsupport" runat="server" Text='<%#Eval("YourSupportRequest") %>'/>
     </ItemTemplate>
    <EditItemTemplate>
         <asp:TextBox ID="txtsupport" width="30px"  runat="server" Text='<%#Eval("YourSupportRequest") %>'/>
     </EditItemTemplate>
   
 </asp:TemplateField>
                   

                          </Columns>
                 <FooterStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
                <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#FFCC66" ForeColor="#333333" HorizontalAlign="Center" />
                <RowStyle BackColor="#FFFBD6" ForeColor="#333333" />
                <SelectedRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="Navy" />
                <SortedAscendingCellStyle BackColor="#FDF5AC" />
                <SortedAscendingHeaderStyle BackColor="#4D0000" />
                <SortedDescendingCellStyle BackColor="#FCF6C0" />
                <SortedDescendingHeaderStyle BackColor="#820000" />
                 </asp:GridView>

        </div>
        <asp:Label ID="lblmsg" runat="server"></asp:Label>
    </form>
</body>
</html>

